retrieve_task:
  description: >
    Retrieve the most relevant information from the available sources for the user query: {query}.
  expected_output: >
    most relevant information about the user query {query}
  agent: retriever_agent

response_task:
  description: >
    Synthesize the final response for the user query: {query}
  expected_output: >
    A concise and coherent response based on the retrieved infromation from the right source for the user query: {query}. If you are not ble to retrieve the information then respond with "I'm sorry, I couldn't find the information you're looking for."
  agent: response_synthesizer_agent
